import json

from app.services.workers.base import BaseWorker, GeneratedFile, WorkerContext, WorkerResult


class ScrapingWorker(BaseWorker):
    async def generate(self, context: WorkerContext) -> WorkerResult:
        llm_result = await self.generate_with_llm(SCRAPING_SYSTEM_PROMPT, _build_scraping_prompt(context))
        if llm_result:
            return llm_result

        target_url = context.job.external_url
        script = _build_crawler_script(target_url)
        readme = _build_readme(context)
        sample_output = {
            "records": [
                {
                    "title": "Replace this parser with target-specific extraction",
                    "url": target_url,
                    "notes": "The generated script is isolated and not executed automatically by AI-FOS.",
                }
            ]
        }
        return WorkerResult(
            files=[
                GeneratedFile("crawler.py", script),
                GeneratedFile("README.md", readme),
                GeneratedFile("sample_output.json", json.dumps(sample_output, indent=2)),
            ],
            summary="Generated isolated Python crawler scaffold with CSV/JSON export.",
        )


SCRAPING_SYSTEM_PROMPT = """
You are AI-FOS ScrapingWorker.
Generate isolated, reviewable Python scraping deliverables. AI-FOS will only syntax-check the code, not execute it.
Return only valid JSON with this shape:
{
  "summary": "short delivery summary",
  "files": [
    {"path": "crawler.py", "content": "standalone Python code"},
    {"path": "README.md", "content": "usage and review notes"},
    {"path": "sample_output.json", "content": "example JSON output"}
  ]
}
Rules:
- crawler.py must be standalone and compile with python -m py_compile.
- Prefer httpx, csv, json, pathlib, argparse, and standard library helpers.
- Include TODO comments only for target-specific selectors that need operator review.
- Do not run the target site or claim live results.
- Do not include markdown fences around the JSON response.
""".strip()


def _build_scraping_prompt(context: WorkerContext) -> str:
    stack = ", ".join(context.job.tech_stack or []) or "Python"
    return (
        f"Job title: {context.job.title}\n"
        f"Target/source URL: {context.job.external_url}\n"
        f"Stack hints: {stack}\n"
        f"Job description:\n{context.job.description_raw}\n\n"
        f"Operator instructions:\n{context.instructions or 'None'}\n\n"
        f"Previous QA report:\n{context.previous_qa_report or 'None'}\n\n"
        "Generate crawler.py, README.md, and sample_output.json."
    )


def _build_crawler_script(target_url: str) -> str:
    return f'''"""Standalone crawler scaffold generated by AI Freelancer OS.

The script is intentionally not executed by AI-FOS. Review selectors, login
requirements, robots.txt, and customer authorization before running it.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import httpx


DEFAULT_URL = "{target_url}"


def fetch_html(url: str) -> str:
    headers = {{
        "User-Agent": "Mozilla/5.0 (compatible; AI-FOS-Crawler/0.1; +https://dancru.cloud)"
    }}
    with httpx.Client(timeout=30.0, follow_redirects=True, headers=headers) as client:
        response = client.get(url)
        response.raise_for_status()
        return response.text


def extract_records(html: str, source_url: str) -> list[dict[str, str]]:
    # TODO: Replace this conservative placeholder with target-specific selectors.
    title = "Untitled page"
    marker_start = html.lower().find("<title>")
    marker_end = html.lower().find("</title>")
    if marker_start >= 0 and marker_end > marker_start:
        title = html[marker_start + len("<title>"):marker_end].strip() or title

    return [
        {{
            "title": title,
            "source_url": source_url,
            "raw_length": str(len(html)),
        }}
    ]


def write_json(records: list[dict[str, str]], path: Path) -> None:
    path.write_text(json.dumps(records, indent=2, ensure_ascii=False), encoding="utf-8")


def write_csv(records: list[dict[str, str]], path: Path) -> None:
    if not records:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(records[0].keys()))
        writer.writeheader()
        writer.writerows(records)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--url", default=DEFAULT_URL)
    parser.add_argument("--out", default="output.json")
    args = parser.parse_args()

    html = fetch_html(args.url)
    records = extract_records(html, args.url)
    output_path = Path(args.out)
    if output_path.suffix.lower() == ".csv":
        write_csv(records, output_path)
    else:
        write_json(records, output_path)


if __name__ == "__main__":
    main()
'''


def _build_readme(context: WorkerContext) -> str:
    return (
        f"# Scraping Worker Output\n\n"
        f"Job: {context.job.title}\n\n"
        "## Files\n"
        "- `crawler.py`: standalone crawler scaffold.\n"
        "- `sample_output.json`: example output shape.\n\n"
        "## Review Checklist\n"
        "- Confirm the target URL and selectors with the client.\n"
        "- Confirm login, proxy, CAPTCHA, and rate-limit requirements.\n"
        "- Run only after authorization; AI-FOS only checks syntax automatically.\n"
    )
